config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get 'home/index'

  resources :contents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user

  validates :title, :description, presence: true

  has_many :tag_contents, dependent: :destroy
  has_many :tags, through: :tag_contents
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true, uniqueness: { scope: :user_id }

  has_many :tag_contents, dependent: :destroy
  has_many :contents, through: :tag_contents
end

app/models/tag_content.rb
class TagContent < ApplicationRecord
  belongs_to :tag
  belongs_to :content
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :contents
  has_many :tags
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/contents_controller.rb
# frozen_string_literal: true

class ContentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_content, only: %i[show edit update destroy]

  def index
    @contents = current_user.contents

    tag_names = params[:tags]

    if tag_names.present?
      @contents = @contents.joins(:tags).where(tags: { name: tag_names}).distinct
    end
  end

  def show
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
  end

  def new
    @content = Content.new
  end

  def create
    @content = current_user.contents.build(content_params)

    if @content.save
      associate_tags!

      redirect_to contents_path, notice: 'Content successfully created!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @content.update(content_params)
      associate_tags!

      redirect_to contents_path, notice: 'Content successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @content.destroy

    redirect_to contents_path, notice: 'Content successfully destroy'
  end

  private

  def set_content
    @content = Content.find(params[:id])
  end

  def tags_params
    params.require(:content).permit(tags: [])[:tags].reject(&:blank?)
  end

  def content_params
    params.require(:content).permit(:title, :description)
  end

  def associate_tags!
    tags = tags_params.map do |tag_name|
      current_user.tags.where(name: tag_name).first_or_initialize
    end

    @content.tags = tags
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @tags_data = current_user.contents.joins(:tags).group('tags.name').count
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contents/_form.html.erb
<% if content.errors.any? %>
  Errors:<%= content.errors.full_messages.join(', ')%>
<% end %>

<%= form_with(model: content, local:true) do |form| %>
  <div class='form-group'>
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control'  %>
  </div>
  <div class='form-group'>
    <%= form.label :tags %>
    <%= form.select :tags, options_for_select(current_user.tags.pluck(:name), content.tags.pluck(:name)), {}, { class: 'select2 form-control', multiple: 'multiple'} %>
  </div>
  <BR>

  <div class='form-group'>
    <%= form.submit 'Save', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Edit Content</h1>

<%= render 'form', content: @content %>

app/views/contents/index.html.erb
<h1>Contents</h1>

<%= form_tag(contents_path, method: :get) do %>
  <div class='form-group'>
    <%= label_tag :tags %>
    <%= select_tag 'tags[]', options_for_select(current_user.tags.pluck(:name), params[:tags]), { class: 'select2 form-control', multiple: 'multiple'} %>
  </div>
  <BR>
  <div class='actions'>
    <%= submit_tag 'Search', class: "btn btn-primary" %>
  </div>
<% end %>
  <BR>
<%= link_to 'New Content', new_content_path, class: "btn btn-primary" %>
  <BR>
  <BR>
<% @contents.each do |content| %>
  <table class="table table-hover">
    <thead>
      <tr >
        <th scope="col" style='width: 300px' class= "navbar-brand">Title</th>
        <th scope="col" style='width: 300px' class= "navbar-brand">Description</th>
        <th scope="col" style='width: 300px' class= "navbar-brand">Tags</th>
      </tr>
    </thead>
    <td scope="row">
      <%= content.title %>
    </td>
    <td>
      <%= truncate(content.description, length: 15) %>
    </td>
    <td>
      <%= content.tags.pluck(:name).join(', ') %>
    </td>
    <td>
      <%= link_to 'Show', content_path(content), class: "navbar-brand" %>
      <%= link_to 'Edit', edit_content_path(content), class: "navbar-brand" %>
      <%= link_to 'Destroy', content_path(content), method: :delete, data: {confirm: 'Are you sure?'}, class: "navbar-brand" %>
    </td>
  </table>
  <BR>
<% end %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

app/views/contents/show.html.erb
<h1><%= @content.title %></h1>

<%= raw @markdown.render(@content.description) %>

app/views/home/index.html.erb
<h1>Cloud Tags</h1>

<% @tags_data.each do |tag_name, count| %>
  <% font_size = count * 20 %>
  <span style='font-size: <%= font_size > 70 ? 70 : font_size %>px'>
     <%= link_to tag_name, contents_path(tags: [tag_name]), style: 'text-decoration: none' %>
  </span> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MindApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <% if user_signed_in? %>
          <%= link_to 'Home', home_index_path, class: "navbar-brand" %>
          <%= link_to 'Contents', contents_path, class: "navbar-brand" %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-brand" %>
        <% end %>
      </nav>
        <%= yield %>      
    </div>
  </body>
</html>